apiVersion: v1
kind: Service
metadata:
  name: wso2-mi-hospital-int
spec:
  selector:
    app: wso2-mi-hospital-int
  ports:
    - protocol: TCP
      port: 8290
      targetPort: 8290
  type: ClusterIP